x-airflow-common: &airflow-common
  build: .
  image: churn-airflow:0.1
  env_file:
    - .env
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins
    - ./mlruns:/opt/mlruns
    - ./src:/opt/project/src
    - ./api:/opt/project/api
    - ./models:/opt/project/models
    - ./data:/opt/project/data
  user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-0}"
  depends_on:
    - postgres
    - redis

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler

  airflow-triggerer:
    <<: *airflow-common
    command: triggerer

  jupyter:
    <<: *airflow-common
    working_dir: /opt/project
    command: bash -lc "jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --ServerApp.token=''"
    volumes:
      - ./:/opt/project 
    ports:
      - "8888:8888"

volumes:
  postgres-data:
